/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/*.js"],
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      white: "#FBF8DD",
      white2: "#ffffff",
      body: "#3d3737",
      gray: "#d4d3d3",
      primary: "#C63D2F",
      secondary: "#FFBB5C",
      darkOrange: "#E25E3E",
      lightOrange: "#FF9B50",
      hovWhite: "#f8f4f1",
      hovPrimary: "#9e3126",
      lightGray: "#e5e5e5",
      darkPrimary: "#9e3126",
      darkGray: "#6a6a6a",
      lightOrange2: "#ffd7b9",
      placeholder: "#949494",
      black: "#000000",
      medOrange: "#e87e65",
      gradientBegin: "#f6d365",
      gradientEnd: "#fda085",
    },
    extend: {},
  },
  plugins: [],
};
